dubbo:
  application:
    name: user-service-provider
  registry:
    protocol: zookeeper
    address: 192.168.43.145:2181
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: registry
server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: root
